version: "3.2"
services:
  db:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: booked-db
  web:
    build:
      context: './booked-2.8.5/'
      args:
        PHP_MOD: ${PHP_MOD}
        PHP_VERSION: ${PHP_VERSION}
        INSTALLATION_PASSWORD: ${INSTALLATION_PASSWORD}
        PWD_USR: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - frontend
      - backend
    ports:
      - "50001:80"
    restart: always
    container_name: booked-web
networks:
  frontend:
  backend:

